/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_01;
import java.sql.*;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Alan
 */
public class Cliente extends javax.swing.JFrame {
    

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_IDC = new javax.swing.JLabel();
        lbNombC = new javax.swing.JLabel();
        lb_ApellidoC = new javax.swing.JLabel();
        lbTelefonoC = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        btSubirC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        btBajarC = new javax.swing.JButton();
        btBuscarC = new javax.swing.JButton();
        lbAtras_C = new javax.swing.JLabel();
        btModificarC = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("CLIENTE");

        lb_IDC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_IDC.setText("ID");

        lbNombC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbNombC.setText("Nombre");

        lb_ApellidoC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_ApellidoC.setText("Apellido");

        lbTelefonoC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbTelefonoC.setText("Telefono");

        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        btSubirC.setText("Subir Datos");
        btSubirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirCActionPerformed(evt);
            }
        });

        tbCliente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Cliente", "Nombre", "Apellido", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tbCliente);

        btBajarC.setText("Dar de baja");
        btBajarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajarCActionPerformed(evt);
            }
        });

        btBuscarC.setText("Buscar");
        btBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCActionPerformed(evt);
            }
        });

        lbAtras_C.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbAtras_C.setText("Atras <<<");

        btModificarC.setText("Modificar Datos");
        btModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbTelefonoC)
                    .addComponent(lb_ApellidoC)
                    .addComponent(lbNombC))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfNombre)
                    .addComponent(tfApellido)
                    .addComponent(tfTelefono))
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btBajarC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSubirC, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btBuscarC, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lb_IDC)
                                .addGap(18, 18, 18)
                                .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btModificarC))
                .addGap(46, 46, 46))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lbAtras_C, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(36, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAtras_C, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lbNombC)
                                    .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(21, 21, 21)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lb_ApellidoC)
                                    .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btSubirC)
                                    .addComponent(lb_IDC)
                                    .addComponent(tfID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(btBuscarC))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(btBajarC)))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefonoC)
                    .addComponent(tfTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarC))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(95, 95, 95))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 46, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoActionPerformed

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void btSubirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirCActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/poo_ventas?useSSL=false","root","");//establece la conexion con la BD
            PreparedStatement pst= cn.prepareStatement("insert into clientes values(?,?,?,?)");//Valores que se insertaran en la tabla "nombre_tabla"
            pst.setString(1,"0");
            pst.setString(2,tfNombre.getText().trim());
            pst.setString(3,tfApellido.getText().trim());
            pst.setString(4,tfTelefono.getText().trim());
            pst.executeUpdate();
            
             
            tfNombre.setText("");
            tfApellido.setText("");
            tfTelefono.setText("");
            
            JOptionPane.showMessageDialog(null,"Registro Exitoso", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
            MostrarClientes();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSubirCActionPerformed

    private void btBajarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajarCActionPerformed
        
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/poo_ventas?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("delete from clientes where id_cliente= ?");
            
            pst.setString(1, tfID.getText().trim());
            pst.executeUpdate();
           tfNombre.setText("");
           tfApellido.setText("");
           tfTelefono.setText("");
           
           JOptionPane.showMessageDialog(null,"Registro eliminado", "Registro eliminado", JOptionPane.INFORMATION_MESSAGE);
           MostrarClientes();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btBajarCActionPerformed

    private void btBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCActionPerformed
            try {
         Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/poo_ventas?useSSL=false","root","");
         PreparedStatement pst= cn.prepareStatement("select * from clientes where id_cliente= ?");
         pst.setString(1,tfID.getText().trim());
         ResultSet rs= pst.executeQuery();//ResultSet es para consultar los datos
                if (rs.next()) {
                    tfNombre.setText(rs.getString("nombre"));
                    tfApellido.setText(rs.getString("apellido"));
                    tfTelefono.setText(rs.getString("telefono"));
                } else {
                    JOptionPane.showMessageDialog(null,"Cliente no encontrado","Cliente no encontrado",JOptionPane.INFORMATION_MESSAGE);
                    
                }
         
         
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_btBuscarCActionPerformed

    private void btModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarCActionPerformed
        try {
            String id= tfID.getText().trim();
            
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/poo_ventas?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("update clientes set nombre=?, apellido=?, telefono=? where id_cliente="+id);
            pst.setString(1,tfNombre.getText().trim());
            pst.setString(2, tfApellido.getText().trim());
            pst.setString(3,tfTelefono.getText().trim());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro modificado","Registro modificado",JOptionPane.INFORMATION_MESSAGE);
            MostrarClientes();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btModificarCActionPerformed

    public void MostrarClientes(){
        try {
            
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/poo_ventas?useSSL=false","root","");
            Statement stm=cn.createStatement();
            ResultSet rs =stm.executeQuery("select * from clientes");
            tbCliente.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
        
        
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBajarC;
    private javax.swing.JButton btBuscarC;
    private javax.swing.JButton btModificarC;
    private javax.swing.JButton btSubirC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbAtras_C;
    private javax.swing.JLabel lbNombC;
    private javax.swing.JLabel lbTelefonoC;
    private javax.swing.JLabel lb_ApellidoC;
    private javax.swing.JLabel lb_IDC;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfTelefono;
    // End of variables declaration//GEN-END:variables
}
