/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_01;
import java.sql.*;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import conexion.Conexion;
import java.util.logging.Level;
import java.util.logging.Logger;
/**
 *
 * @author Alan
 */
public class Vendedores extends javax.swing.JFrame {
    Connection conexion;
    Conexion cone= new Conexion();
    /**
     * Creates new form Vendedores
     */
    public Vendedores() {
        initComponents();
        this.setLocationRelativeTo(null);
        MostrarVendedores();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbID = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbApellido = new javax.swing.JLabel();
        lbEspecialidad = new javax.swing.JLabel();
        lbComision = new javax.swing.JLabel();
        tfIDBusqueda = new javax.swing.JTextField();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfEspecialidad = new javax.swing.JTextField();
        tfComision = new javax.swing.JTextField();
        btModificarDatos = new javax.swing.JButton();
        btBajarDatos = new javax.swing.JButton();
        btSubirDatos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbVendedores = new javax.swing.JTable();
        btBuscar = new javax.swing.JButton();
        lbContraseña = new javax.swing.JLabel();
        tfContraseña = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel6.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel6.setText("Atras <<<");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("VENDEDORES");

        lbID.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbID.setText("ID");

        lbNombre.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbNombre.setText("Nombre");

        lbApellido.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbApellido.setText("Apellido");

        lbEspecialidad.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbEspecialidad.setText("Especialidad");

        lbComision.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbComision.setText("Comisión");

        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfEspecialidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEspecialidadActionPerformed(evt);
            }
        });

        btModificarDatos.setText("Modificar Datos");
        btModificarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarDatosActionPerformed(evt);
            }
        });

        btBajarDatos.setText("Dar de baja");
        btBajarDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajarDatosActionPerformed(evt);
            }
        });

        btSubirDatos.setText("Subir Datos");
        btSubirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirDatosActionPerformed(evt);
            }
        });

        tbVendedores.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tbVendedores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID_Vendedor", "Nombre", "Apellido", "Especialidad", "Comisión"
            }
        ));
        jScrollPane1.setViewportView(tbVendedores);

        btBuscar.setText("Buscar");
        btBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarActionPerformed(evt);
            }
        });

        lbContraseña.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbContraseña.setText("Contraseña");

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEspecialidad)
                            .addComponent(lbApellido)
                            .addComponent(lbNombre)
                            .addComponent(lbComision)
                            .addComponent(lbContraseña))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tfNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                            .addComponent(tfApellido)
                            .addComponent(tfEspecialidad)
                            .addComponent(tfComision)
                            .addComponent(tfContraseña))
                        .addGap(75, 75, 75)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btModificarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btBajarDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btSubirDatos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(65, 65, 65))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbID)
                        .addGap(18, 18, 18)))
                .addComponent(tfIDBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btBuscar)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(181, 181, 181)
                                    .addComponent(jLabel1))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbID)
                            .addComponent(tfIDBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(29, 29, 29)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbNombre)
                                        .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbApellido)
                                        .addComponent(tfApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(23, 23, 23)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbEspecialidad)
                                        .addComponent(tfEspecialidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btModificarDatos)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(82, 82, 82)
                                .addComponent(btBajarDatos))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(btSubirDatos)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbComision)
                            .addComponent(tfComision, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbContraseña)
                    .addComponent(tfContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfEspecialidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEspecialidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEspecialidadActionPerformed

    private void btModificarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarDatosActionPerformed
        try {
            String id= tfIDBusqueda.getText().trim();
            conexion=cone.getConexion();
            PreparedStatement pst= conexion.prepareStatement("update vendedor set nombre=?, apellido=?, especialdad=?, comisión=?, contraseña=? where id_vendedor="+id);
            pst.setString(1, tfNombre.getText().trim());
            pst.setString(2, tfApellido.getText().trim());
            pst.setString(3, tfEspecialidad.getText().trim());
            pst.setString(4, tfComision.getText().trim());
            pst.setString(5, tfContraseña.getText().trim());
            pst.executeUpdate();
            JOptionPane.showMessageDialog(null,"Registro modificado","Registro modificado",JOptionPane.INFORMATION_MESSAGE);
            MostrarVendedores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
        
        
    }//GEN-LAST:event_btModificarDatosActionPerformed

    private void btBajarDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajarDatosActionPerformed
        try {
            conexion= cone.getConexion();
            PreparedStatement pst= conexion.prepareStatement("delete from vendedor where id_vendedor= ?");
            pst.setString(1, tfIDBusqueda.getText().trim());
            pst.executeUpdate();
            tfNombre.setText("");
            tfApellido.setText("");
            tfEspecialidad.setText("");
            tfComision.setText("");
            tfContraseña.setText("");
            
            JOptionPane.showMessageDialog(null,"Registro eliminado", "Registro eliminado", JOptionPane.INFORMATION_MESSAGE);
            MostrarVendedores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btBajarDatosActionPerformed

    private void btSubirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirDatosActionPerformed
        
        try {
            conexion=cone.getConexion();
            PreparedStatement pst= conexion.prepareStatement("insert into vendedor values(?,?,?,?,?,?)");
            pst.setString(1,"0");
            pst.setString(2, tfNombre.getText().trim());
            pst.setString(3, tfApellido.getText().trim());
            pst.setString(4, tfEspecialidad.getText().trim());
            pst.setString(5, tfComision.getText().trim());
            pst.setString(6, tfContraseña.getText().trim());
            pst.executeUpdate();
            tfNombre.setText("");
            tfApellido.setText("");
            tfEspecialidad.setText("");
            tfComision.setText("");
            tfContraseña.setText("");
            JOptionPane.showMessageDialog(null,"Registro exitoso","Registro exitoso",JOptionPane.INFORMATION_MESSAGE);
            MostrarVendedores();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btSubirDatosActionPerformed

    private void btBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarActionPerformed
        try {
        conexion= cone.getConexion();
        PreparedStatement pst= conexion.prepareStatement("select * from vendedor where id_vendedor= ?");
        pst.setString(1, tfIDBusqueda.getText().trim());
        ResultSet rs=pst.executeQuery();
            if (rs.next()) {
                tfNombre.setText(rs.getString("nombre"));
                tfApellido.setText(rs.getString("apellido"));
                tfEspecialidad.setText(rs.getString("especialdad"));
                tfComision.setText(rs.getString("comisión"));
                tfContraseña.setText(rs.getString("contraseña"));
            } else{
                JOptionPane.showMessageDialog(null,"Cliente no encontrado","Cliente no encontrado",JOptionPane.INFORMATION_MESSAGE);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btBuscarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    tfApellido.setText("");
    tfComision.setText("");
    tfEspecialidad.setText("");
    tfIDBusqueda.setText("");
    tfNombre.setText("");
    tfContraseña.setText("");
    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
    Interfaz inte= new Interfaz();
    inte.setVisible(true);
    this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    /**
     * @param args the command line arguments
     */
     public void MostrarVendedores(){
        try {
            
            conexion=cone.getConexion();
            Statement stm=conexion.createStatement();
            ResultSet rs =stm.executeQuery("select * from vendedor");
            tbVendedores.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Error","Error de conexion",JOptionPane.ERROR_MESSAGE);
        }
  }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vendedores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vendedores().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBajarDatos;
    private javax.swing.JButton btBuscar;
    private javax.swing.JButton btModificarDatos;
    private javax.swing.JButton btSubirDatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbApellido;
    private javax.swing.JLabel lbComision;
    private javax.swing.JLabel lbContraseña;
    private javax.swing.JLabel lbEspecialidad;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JTable tbVendedores;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfComision;
    private javax.swing.JTextField tfContraseña;
    private javax.swing.JTextField tfEspecialidad;
    private javax.swing.JTextField tfIDBusqueda;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables
}
