/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bd_01;
import java.sql.*;
/**
 *
 * @author Alan
 */
public class Venta extends javax.swing.JFrame {

    /**
     * Creates new form Venta
     */
    public Venta() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbAtras_C = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lbNombC = new javax.swing.JLabel();
        lb_ApellidoC = new javax.swing.JLabel();
        lbTelefonoC = new javax.swing.JLabel();
        tfNombre = new javax.swing.JTextField();
        tfApellido = new javax.swing.JTextField();
        tfTelefono = new javax.swing.JTextField();
        btSubirC = new javax.swing.JButton();
        btBajarC = new javax.swing.JButton();
        btModificarC = new javax.swing.JButton();
        lb_IDC = new javax.swing.JLabel();
        tfID = new javax.swing.JTextField();
        btBuscarC = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        lbAtras_C1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbNombC1 = new javax.swing.JLabel();
        lb_ApellidoC1 = new javax.swing.JLabel();
        lbTelefonoC1 = new javax.swing.JLabel();
        tfNombre1 = new javax.swing.JTextField();
        tfApellido1 = new javax.swing.JTextField();
        tfTelefono1 = new javax.swing.JTextField();
        btSubirC1 = new javax.swing.JButton();
        btBajarC1 = new javax.swing.JButton();
        btModificarC1 = new javax.swing.JButton();
        lb_IDC1 = new javax.swing.JLabel();
        tfID1 = new javax.swing.JTextField();
        btBuscarC1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente1 = new javax.swing.JTable();

        lbAtras_C.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbAtras_C.setText("Atras <<<");

        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel1.setText("CLIENTE");

        lbNombC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbNombC.setText("Nombre");

        lb_ApellidoC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_ApellidoC.setText("Apellido");

        lbTelefonoC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbTelefonoC.setText("Telefono");

        tfApellido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellidoActionPerformed(evt);
            }
        });

        tfTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefonoActionPerformed(evt);
            }
        });

        btSubirC.setText("Subir Datos");
        btSubirC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirCActionPerformed(evt);
            }
        });

        btBajarC.setText("Dar de baja");
        btBajarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajarCActionPerformed(evt);
            }
        });

        btModificarC.setText("Modificar Datos");
        btModificarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarCActionPerformed(evt);
            }
        });

        lb_IDC.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_IDC.setText("ID_Cliente");

        btBuscarC.setText("Buscar");
        btBuscarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarCActionPerformed(evt);
            }
        });

        tbCliente.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Cliente", "Nombre", "Apellido", "Telefono"
            }
        ));
        jScrollPane1.setViewportView(tbCliente);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        lbAtras_C1.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lbAtras_C1.setText("Atras <<<");

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setText("VENTA");

        lbNombC1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbNombC1.setText("Nombre");

        lb_ApellidoC1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_ApellidoC1.setText("Apellido");

        lbTelefonoC1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lbTelefonoC1.setText("Telefono");

        tfApellido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfApellido1ActionPerformed(evt);
            }
        });

        tfTelefono1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfTelefono1ActionPerformed(evt);
            }
        });

        btSubirC1.setText("Subir Datos");
        btSubirC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSubirC1ActionPerformed(evt);
            }
        });

        btBajarC1.setText("Dar de baja");
        btBajarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBajarC1ActionPerformed(evt);
            }
        });

        btModificarC1.setText("Modificar Datos");
        btModificarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarC1ActionPerformed(evt);
            }
        });

        lb_IDC1.setFont(new java.awt.Font("Agency FB", 1, 18)); // NOI18N
        lb_IDC1.setText("ID_Cliente");

        btBuscarC1.setText("Buscar");
        btBuscarC1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btBuscarC1ActionPerformed(evt);
            }
        });

        tbCliente1.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        tbCliente1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID_Cliente", "Nombre", "Apellido", "Telefono"
            }
        ));
        jScrollPane2.setViewportView(tbCliente1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(355, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(332, 332, 332))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(161, 161, 161)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbTelefonoC1)
                                .addComponent(lb_ApellidoC1)
                                .addComponent(lbNombC1))
                            .addGap(26, 26, 26)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(tfNombre1)
                                .addComponent(tfApellido1)
                                .addComponent(tfTelefono1))
                            .addGap(59, 59, 59)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btBajarC1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btSubirC1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                                    .addGap(46, 46, 46)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(btBuscarC1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(lb_IDC1)
                                            .addGap(18, 18, 18)
                                            .addComponent(tfID1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(btModificarC1))
                            .addGap(21, 21, 21))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(lbAtras_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 612, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(22, 22, 22)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel2)
                .addContainerGap(480, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(63, 63, 63)
                    .addComponent(lbAtras_C1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(40, 40, 40)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lbNombC1)
                                        .addComponent(tfNombre1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(21, 21, 21)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lb_ApellidoC1)
                                        .addComponent(tfApellido1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btSubirC1)
                                        .addComponent(lb_IDC1)
                                        .addComponent(tfID1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addComponent(btBuscarC1))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btBajarC1)))
                    .addGap(21, 21, 21)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbTelefonoC1)
                        .addComponent(tfTelefono1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btModificarC1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(63, 63, 63)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfApellidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellidoActionPerformed

    private void tfTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefonoActionPerformed

    private void btSubirCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirCActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");//establece la conexion con la BD
            PreparedStatement pst= cn.prepareStatement("insert into cliente values(?,?,?,?)");//Valores que se insertaran en la tabla "nombre_tabla"
            pst.setString(1,"0");
            pst.setString(2,tfNombre.getText().trim());
            pst.setString(3,tfApellido.getText().trim());
            pst.setString(4,tfTelefono.getText().trim());
            pst.executeUpdate();

            tfNombre.setText("");
            tfApellido.setText("");
            tfTelefono.setText("");
            //lbStatus.setText("Registro exitoso!!");
          //  MostrarClientes();

        }catch(Exception e){
        }
    }//GEN-LAST:event_btSubirCActionPerformed

    private void btBajarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajarCActionPerformed

        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("delete from cliente where ID= ?");

            pst.setString(1, tfID.getText().trim());
            pst.executeUpdate();
            tfNombre.setText("");
            tfApellido.setText("");
            tfTelefono.setText("");

          //  lbStatus.setText("Datos Borrados");
            //MostrarClientes();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btBajarCActionPerformed

    private void btModificarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarCActionPerformed
        try {
            String id= tfID.getText().trim();

            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("update cliente set Nom=?, Ape=?, Tel=? where ID="+id);
            pst.setString(1,tfNombre.getText().trim());
            pst.setString(2, tfApellido.getText().trim());
            pst.setString(3,tfTelefono.getText().trim());
            pst.executeUpdate();

           // lbStatus.setText("Modificación exitosa");
            //MostrarClientes();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btModificarCActionPerformed

    private void btBuscarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarCActionPerformed
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("select * from cliente where ID= ?");
            pst.setString(1,tfID.getText().trim());
            ResultSet rs= pst.executeQuery();
            if (rs.next()) {
                tfNombre.setText(rs.getString("Nom"));
                tfApellido.setText(rs.getString("Ape"));
                tfTelefono.setText(rs.getString("Tel"));
            } else {
               // JOptionPane.showMessageDialog(null,"cliente no registrado");

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btBuscarCActionPerformed

    private void tfApellido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfApellido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfApellido1ActionPerformed

    private void tfTelefono1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfTelefono1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfTelefono1ActionPerformed

    private void btSubirC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSubirC1ActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");//establece la conexion con la BD
            PreparedStatement pst= cn.prepareStatement("insert into cliente values(?,?,?,?)");//Valores que se insertaran en la tabla "nombre_tabla"
            pst.setString(1,"0");
            pst.setString(2,tfNombre.getText().trim());
            pst.setString(3,tfApellido.getText().trim());
            pst.setString(4,tfTelefono.getText().trim());
            pst.executeUpdate();

            tfNombre.setText("");
            tfApellido.setText("");
            tfTelefono.setText("");
           // lbStatus.setText("Registro exitoso!!");
            //MostrarClientes();

        }catch(Exception e){
        }
    }//GEN-LAST:event_btSubirC1ActionPerformed

    private void btBajarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBajarC1ActionPerformed

        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("delete from cliente where ID= ?");

            pst.setString(1, tfID.getText().trim());
            pst.executeUpdate();
            tfNombre.setText("");
            tfApellido.setText("");
            tfTelefono.setText("");

            //lbStatus.setText("Datos Borrados");
           // MostrarClientes();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btBajarC1ActionPerformed

    private void btModificarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarC1ActionPerformed
        try {
            String id= tfID.getText().trim();

            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("update cliente set Nom=?, Ape=?, Tel=? where ID="+id);
            pst.setString(1,tfNombre.getText().trim());
            pst.setString(2, tfApellido.getText().trim());
            pst.setString(3,tfTelefono.getText().trim());
            pst.executeUpdate();

           // lbStatus.setText("Modificación exitosa");
           // MostrarClientes();

        } catch (Exception e) {

        }
    }//GEN-LAST:event_btModificarC1ActionPerformed

    private void btBuscarC1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btBuscarC1ActionPerformed
        try {
            Connection cn= DriverManager.getConnection("jdbc:mysql://localhost:3307/factura?useSSL=false","root","");
            PreparedStatement pst= cn.prepareStatement("select * from cliente where ID= ?");
            pst.setString(1,tfID.getText().trim());
            ResultSet rs= pst.executeQuery();
            if (rs.next()) {
                tfNombre.setText(rs.getString("Nom"));
                tfApellido.setText(rs.getString("Ape"));
                tfTelefono.setText(rs.getString("Tel"));
            } else {
                //JOptionPane.showMessageDialog(null,"cliente no registrado");

            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btBuscarC1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btBajarC;
    private javax.swing.JButton btBajarC1;
    private javax.swing.JButton btBuscarC;
    private javax.swing.JButton btBuscarC1;
    private javax.swing.JButton btModificarC;
    private javax.swing.JButton btModificarC1;
    private javax.swing.JButton btSubirC;
    private javax.swing.JButton btSubirC1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbAtras_C;
    private javax.swing.JLabel lbAtras_C1;
    private javax.swing.JLabel lbNombC;
    private javax.swing.JLabel lbNombC1;
    private javax.swing.JLabel lbTelefonoC;
    private javax.swing.JLabel lbTelefonoC1;
    private javax.swing.JLabel lb_ApellidoC;
    private javax.swing.JLabel lb_ApellidoC1;
    private javax.swing.JLabel lb_IDC;
    private javax.swing.JLabel lb_IDC1;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbCliente1;
    private javax.swing.JTextField tfApellido;
    private javax.swing.JTextField tfApellido1;
    private javax.swing.JTextField tfID;
    private javax.swing.JTextField tfID1;
    private javax.swing.JTextField tfNombre;
    private javax.swing.JTextField tfNombre1;
    private javax.swing.JTextField tfTelefono;
    private javax.swing.JTextField tfTelefono1;
    // End of variables declaration//GEN-END:variables
}
